apiVersion: apps/v1
kind: Deployment
metadata:
  name: bipedal-es-worker-pod
spec:
  selector:
    matchLabels:
      app: bipedal-es-worker-pod
  replicas: 1000
  template:
    metadata:
      labels:
        app: bipedal-es-worker-pod
    spec:
      containers:
      - name: bipedal-es-worker
        image: gcr.io/${GCLOUD_PROJECT}/es-on-gke:1.0
        resources:
          requests:
            memory: "1.5Gi"
            cpu: "1.0"
          limits:
            memory: "2Gi"
            cpu: "1.2"
        ports:
        - containerPort: 20000
        command: [ "python3", "/app/es_worker.py", "--run-on-gke",
                   "--config=/app/configs/BipedalWalkerHardcore.gin"]
---
apiVersion: v1
kind: Service
metadata:
  name: bipedal-es-worker-service
spec:
  selector:
    app: bipedal-es-worker-pod
  clusterIP: None
  ports:
  - name: grpc
    port: 20000
